
name: CI

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/git
            ~/.cargo/registry
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cargo-llvm-cov
        continue-on-error: true
        uses: taiki-e/install-action@cargo-llvm-cov
          
      - run: cargo llvm-cov --lcov --output-path lcov.info
  
      - uses: codecov/codecov-action@v5
        continue-on-error: true
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
            files: ./lcov.info
